apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-memory
  namespace: USER_ID
spec:
  storageClassName: efs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem