apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-models
  namespace: base-model
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Model registry
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: crazytrain123!
  AWS_DEFAULT_REGION: eu-west-1
  AWS_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  AWS_S3_BUCKET: model-registry