apiVersion: v1
kind: Namespace
metadata:
  name: base-model
  labels:
    modelmesh-enabled: "true"
    opendatahub.io/dashboard: "true"
  annotations:
    openshift.io/display-name: "Base model for traffic sign detection"